matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7.15
  - os: osx
    language: generic
    env: PYTHON=3.6.5

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
    brew install openssl readline
    # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
    # I didn't do this above because it works and I'm lazy.
    brew outdated pyenv || brew upgrade pyenv
    # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
    # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
    # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
    # modify the Bash environment. ??? So, I hand-set the variables instead.
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
  fi
  
install:
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - python -m pip install wheel numpy scipy matplotlib periodictable wxPython bumps
  - python setup.py bdist_wheel

before_deploy: 
  - openssl aes-256-cbc -K $encrypted_b1042ea612e6_key -iv $encrypted_b1042ea612e6_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key 

deploy:
  provider: pages
  skip-cleanup: true
  #github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  github_token:
    secure: Sixubu3FPTCpdRVyzPwIm6M++1rYLgeCGIslJUiGIppFsBnquv6QVed3utFp05zb02Chjhx7DRaoNRsjKabPBkfBK5J80/ttR0Y2ooglhaGOnSxqJYN2XUfdB6l13f9MR/7EkQ64zmIN27REZwuLpRg11XJcp2v8D3bG81jXInstTPRPJzx+TvmOaNkOJ9kQvHJ3DZWUIKINVIDpjxkcS4AHIe6aA3EC0YDRbPBQrjCvoV6t0cpj2dq5yM3ShevSmCA2tI/5vA5GxPOutWpWuO6+Y2sOeamkn1GxGxBBts5YY48LiArkdjJoOTWTjBcKJ95m9hAa9GTbmm+zto4zSHfYc6AnW5nVIP2uu13RmTvsGOmt1UhU6T2DbNUItzZ90ys92KOTlxc20p1hLjw3fuAXBbk4ooNxEf4h7ZswB5u0eKh8DC13Siy9K9L8yGV7t/fEKFmcOGWo5SKQXDqNsnl3KWyTpxVU5PEDmF+nV0gNwDKOY6+mZyMX8mlwW7tFHzSO6U5LSLwa85a8wWbmCvwUvUhdbFVDpqbV9uEfoCi4R/RhEpa6KSdrUSIlsSZ+RQhNigS1WAO6K0V3x5yiE0ZCo7+ABf56mksYFyq1J3qAzSkqp9JdGBGr9zoB9MLklvRQ7lqFHll550YmGQAMRLrEDJdfaPn2hv5MZTB/yx4=
  keep-history: true
  target-branch: dist
  local-dir: dist
  on:
    branch: master
