os: linux

language: python
python:
  - 2.7
  - 3.6

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7.15
  - os: osx
    language: generic
    env: PYTHON=3.6.5

before_install: 
  - openssl aes-256-cbc -K $encrypted_b1042ea612e6_key -iv $encrypted_b1042ea612e6_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key 
  - bash ./brew_update.sh

install:
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - python setup.py bdist_wheel
  
deploy:
  provider: pages
  skip-cleanup: true
  #github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: dist
  local-dir: dist
  on:
    branch: master
