name: Build webview

on:
  workflow_dispatch:

env:
  branch_name: webview

jobs:
  test_and_build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          #- { os: ubuntu-latest, py: 3.8, doc: 1 }
          - { os: windows-latest, py: "3.10", exe: 1, whl: 1 }
          #- { os: macos-latest, py: 3.8, whl: 1 }
          # all using to stable abi

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ env.branch_name }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.config.py }}

    - name: Build installer
      run: |
        pwsh -command ".\$GITHUB_WORKSPACE\extra\build_conda_packed.ps1"
        mkdir artifacts
        pwd
        dir dist
        dir extra
        mv dist\refl1d*.tar.gz "artifacts\"
        mv dist\refl1d*.zip "artifacts\"
        mv dist\refl1d*.exe "artifacts\"

    - name: Update release assets and text
      uses: actions/github-script@v7
      env:
        SEARCH_PATTERN: "artifacts/*"
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const script = require('./.github/actions/update_unstable.js');
          const output = await script({github, context, glob});
          console.log(output);