name: Build webview with Jupyter for macos

on:
  workflow_dispatch:

env:
  branch_name: webview

jobs:
  test_and_build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          #- { os: ubuntu-latest, py: 3.8, doc: 1 }
          # - { os: windows-latest, py: "3.10", exe: 1, whl: 1 }
          # - { os: macos-latest-xlarge, py: "3.10", whl: 1}
          - { os: macos-latest, py: "3.10", whl: 1 }
          # all using to stable abi

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ env.branch_name }}

    - name: Set up Python ${{ matrix.config.py }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.config.py }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.config.py }}

    - name: Build installer
      run: |
        ./extra/build_conda_packed_jupyter.sh
        mkdir unstable
        pwd
        mv refl1d-webview* ./unstable/

    - name: Update release assets and text
      uses: actions/github-script@v7
      env:
        SEARCH_PATTERN: "unstable/*"
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const script = require('./.github/actions/update_unstable.js');
          const output = await script({github, context, glob});
          console.log(output);
