name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { os: ubuntu-latest, py: 2.7 }
          - { os: ubuntu-latest, py: 3.8, doc: 1 }
          # Need mac/windows in all varieties in order to build wheels.
          # TODO: switch to stable abi
          - { os: windows-latest, py: 3.6 }
          - { os: windows-latest, py: 3.7 }
          - { os: windows-latest, py: 3.8 }
          - { os: windows-latest, py: 3.9 }
          - { os: macos-latest, py: 3.6 }
          - { os: macos-latest, py: 3.7 }
          - { os: macos-latest, py: 3.8 }
          - { os: macos-latest, py: 3.9 }

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.cfg.py }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.cfg.py }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install numpy scipy matplotlib bumps periodictable scikit-learn pytest pytest-cov

    - name: Test with pytest
      run: |
        pytest -v

    - name: Check examples
      run: |
        python check_examples.py --chisq

    - name: Build wheel
      run: |
        python setup.py bdist_wheel

    - name: Archive wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: dist/refl1d-*.whl

    - name: Check that the docs build (linux only)
      if: matrix.cfg.doc == 1
      run: |
        python -m pip install sphinx
        make -j 4 -C doc SPHINXOPTS="-W --keep-going" html
